### ISSUE TITLE
User Customization

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#15] opened 2023-07-18 05:08 UTC
Right now the website displays the zmanim according to either the Ohr HaChaim calendar or the Amudei Horaah calendar. There are some setting that have been added to the android and ios apps that help customize what zmanim to show if the user so chooses it. I will make a separate Issue for each setting.

**Comment by NightScript370** [comment] 2023-11-26 17:12
Duplicate of #13

**Closed by NightScript370** 2023-11-26 17:12 UTC
